version: '3'

services:
  db:
    image: postgres
    restart: always
    env_file: docker/db.env
    volumes:
      - database:/var/lib/postgresql/data
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000 --insecure
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: 
      - docker/web.env
      - docker/db.env
    volumes:
      - config:/opt/peering-manager/config
    entrypoint: /opt/docker/entrypoint.sh
volumes:
  database:
    driver: local
  config:
    driver: local